\c mylocaldb;

BEGIN;

TRUNCATE TABLE game.matchUserInfos CASCADE;
TRUNCATE TABLE game.gameUserInfos CASCADE;
TRUNCATE TABLE game.trickUserInfos CASCADE;
TRUNCATE TABLE game.trickTypes CASCADE;
TRUNCATE TABLE game.tricks CASCADE;
TRUNCATE TABLE game.games CASCADE;
TRUNCATE TABLE game.matches CASCADE;
TRUNCATE TABLE account.users CASCADE;

END;

COMMIT;